### ISSUE TITLE
一个报错

### ISSUE THREAD

**Issue by aneric16088** [fermionorz/Boss-Spider#1]
显示list index out of range
第114行，19行，40行

**Comment by aneric16088** [comment]
加一个能不能把岗位描述也爬下来

**Comment by sfdsgSD** [comment]
> 显示list index out of range 第114行，19行，40行

你好，我也是list index out of range第114行，19行，40行

**Comment by fermionorz** [comment]
> 加一个能不能把岗位描述也爬下来

不打算加，因为这个需要打开对应的岗位，要么很慢，要么容易被封。

**Comment by fermionorz** [comment]
报错：list index out of range第114行，19行，40行
请发一份config.py看一下。

**Comment by fermionorz** [comment]
我没复现成功，出现这个错误的可以尝试第二次运行。

**Comment by sfdsgSD** [comment]
> > 加一个能不能把岗位描述也爬下来
> 
> 不打算加，因为这个需要打开对应的岗位，要么很慢，要么容易被封。

你好，请问第一页不能拿到是什么bug呢

**Comment by fermionorz** [comment]
> > > 加一个能不能把岗位描述也爬下来
> > 
> > 
> > 不打算加，因为这个需要打开对应的岗位，要么很慢，要么容易被封。
> 
> 你好，请问第一页不能拿到是什么bug呢

我想应该是设置的睡眠时间比较短，可能还没有加载出来。可以考虑换一个好的网络环境

**Comment by fermionorz** [comment]
> 显示list index out of range 第114行，19行，40行

已修复
